### ISSUE TITLE
NullPointer in DSNSensor.java on line 116

### ISSUE THREAD

**Issue by aarjavshah** [EXXETA/sonar-msgflow-plugin#17]
I'm getting NPE while running the sonar analysis. I'll share the logs and further details on the issue.

**Comment by aarjavshah** [comment]
**Logs:**
```
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at com.exxeta.iss.sonar.msgflow.batch.DSNSensor.analyse(DSNSensor.java:1
16)
```

This was happening because the esql and msgflow files were placed in the subdirectory. To locate the path to esql the package info in the compute expression is used. However, this causes in issue when both msgflow and esql are in the subdirectory. The current implementation uses the package info as a path relative to the message flow.

**Folder Structure for the project:**
```
SampleAPI_v1
     -->operations
          -->getOp1
                -->op1.subflow
                -->op1.esql
```
**Path to esql directory identified as -->** C:\Users\User1\ApiTest\SampleAPI_v1\operations\getOp1\operations.getOp1
This is not existing in the project folder. So,causes NPE when files are loaded under that directory.

This has two problems.
1. The path is relative to the project directory and not the msgflow which refers to the module
2. The package info can not be directly used to path, modification needed to convert that to use it in the path.

**Comment by aarjavshah** [comment]
Fix has been merged. Closing the issue.
