### ISSUE TITLE
Latest version does not support SonarQube 7.3

### ISSUE THREAD

**Issue by JohannBlais** [EXXETA/sonar-msgflow-plugin#20]
Hello,

The plugin does not load on a SonarQube Developer 7.3.
Here is the error message from the web.log

java.lang.IllegalStateException: Fail to load plugin Msgflow [msgflow]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at com.exxeta.iss.sonar.msgflow.MessageFlowPlugin.getExtensions(MessageFlowPlugin.java:96)
	at com.exxeta.iss.sonar.msgflow.MessageFlowPlugin.define(MessageFlowPlugin.java:87)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Sensor
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted

Kind regards

**Comment by marcelhdejong** [comment]
@ThomasPohl I made the necessary changes for this issue. We have upgrade our SonarQube to version 7.3 and tested the upgraded plugin. Can you help me delivering the changes to you via a branch/pull request?

Kind regards,
Marcel
