### ISSUE TITLE
Unable to start the sonar server 7.4 after installing this plugin 1.1.3 and 1.2.0 both

### ISSUE THREAD

**Issue by KuhuADT** [EXXETA/sonar-msgflow-plugin#29]
Hello Team,

I am unable to start the sonarqube server with the provided plugins and below is the error which I have found in logs:

2020.02.20 14:57:04 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2020.02.20 14:57:31 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Msgflow [msgflow]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at com.exxeta.iss.sonar.msgflow.MessageFlowPlugin.getExtensions(MessageFlowPlugin.java:96)
	at com.exxeta.iss.sonar.msgflow.MessageFlowPlugin.define(MessageFlowPlugin.java:87)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Sensor
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted

Can anyone please assist.

**Comment by toanvo729** [comment]
My solution was download the zip file. In the pom file, there is a <sonar.buildVersion>. Updated to your current build version, then compile it. Take the compiled jar file and paste it into SonarQube/extensions/plugins folder.

**Comment by ThomasPohl** [comment]
I will add the sonar versions requirenenrs to the Readme.

**Comment by ThomasPohl** [comment]
I created a wiki page with the prerequisites:
https://github.com/EXXETA/sonar-esql-plugin/wiki

There is no version specialised for sonar 7.4
If you need that I can create a version 1.1.4 or so supporting sonar 7.4

**Comment by ThomasPohl** [comment]
Please check if this is working for you:
https://github.com/EXXETA/sonar-msgflow-plugin/releases/tag/1.1.4-RC1

**Comment by andrewfemin** [comment]
@ThomasPohl I faced the same error with Sonar 8.6 and 1.1.4-RC1 is working for me. Thank you!

**Comment by ThomasPohl** [comment]
@andrewfemin Great. I'll create releases from the candidates.
